name: Hello CI

on:
  push:
    branches: 
      - main

jobs:
  hello:
    runs-on:
      ubuntu-latest
    steps:
      # 1. Hämta koden
      - name: Checkout repository
        uses: actions/checkout@v3

      # 2. Testa workflow
      - name: Hello
        run: echo "Hello CI"