name: Hello CI

# Trigger på push till main
on:
  push:
    branches: 
      - main

jobs:
  hello:
    runs-on: ubuntu-latest
    steps:
      # 1. Hämta koden
      - name: Checkout repository
        uses: actions/checkout@v3

      # 2. Testa workflow
      - name: Say Hello
        run: echo "Hello CI"

      # 3. Extra steg för felsökning (valfritt)
      - name: Show current branch
        run: git branch
